module.exports = {
"38":"Bundesliga|Austria",
"40":"Jupiler League|Netherlands",
"42":"Champions League|Europe",
"43":"Confederations Cup|International",
"44":"Copa America|International",
"45":"Copa Libertadores|Club International",
"46":"SAS Ligaen|Denmark",
"47":"Premier League|England",
"48":"Championship|England",
"50":"EURO Championship|Europe",
"51":"Veikkausliga|Finland",
"53":"Ligue 1|France",
"54":"Bundesliga|Germany",
"55":"Serie A|Italy",
"57":"Eredivisie|Netherlands",
"58":"Play-offs|Netherlands",
"59":"Tippeligaen|Norway",
"61":"Primeira Liga|Portugal",
"64":"Premiership|Scotland",
"67":"Allsvenskan|Sweden",
"71":"Superlig|Turkey",
"73":"UEFA Europa League|Europe",
"74":"UEFA Supercup|Europe",
"77":"World Cup|International",
"78":"World Club Championship|Club International",
"85":"First Division|Denmark",
"86":"Serie B|Italy",
"87":"La Liga|Spain",
"108":"League 1|England",
"109":"League 2|England",
"110":"Ligue 2|France",
"112":"Primera Division|Argentina",
"113":"A-League|Australia",
"114":"Friendlies|International",
"116":"Premier Division|Wales",
"117":"Blue Square Premier|England",
"119":"1 Liga|Austria",
"120":"Super League|China",
"122":"Gambrinus League|Czech Republic",
"124":"League One|Scotland",
"125":"League Two|Scotland",
"126":"Premier Division|Ireland",
"127":"Ligat ha-Al|Israel",
"128":"Liga Leumit|Israel",
"129":"Premiership|Northern Ireland",
"130":"MLS|United States",
"132":"FA Cup|England",
"133":"Carling Cup|England",
"134":"Coupe De France|France",
"137":"Scottish Cup|Scotland",
"138":"Copa del Rey|Spain",
"140":"Segunda Division|Spain",
"141":"Coppa Italia|Italy",
"142":"Football League Cup|England",
"146":"Bundesliga 2|Germany",
"147":"Serie C|Italy",
"163":"Challenge League|Switzerland",
"164":"Swiss Cup|Switzerland",
"165":"Lig 1|Turkey",
"168":"Superettan|Sweden",
"176":"Corgon Liga|Slovakia",
"177":"FA Cup|Slovakia",
"179":"Challenge Cup|Scotland",
"180":"League Cup|Scotland",
"181":"League Play-offs|Scotland",
"182":"Super Liga|Serbia",
"185":"Segunda Liga|Portugal",
"189":"Liga I|Romania",
"196":"Ekstraklasa|Poland",
"203":"Adeccoligaen|Norway",
"206":"The Cup|Norway",
"208":"Bundesliga 3|Germany",
"209":"DFB Pokal|Germany",
"212":"Soproni Liga|Hungary",
"215":"Úrvalsdeild|Iceland",
"216":"1. Deild|Iceland",
"219":"FAI Cup|Ireland",
"220":"League Cup|Ireland",
"222":"Super Cup|Italy",
"223":"J. League|Japan",
"224":"League Cup|Japan",
"230":"Liga MX|Mexico",
"235":"Dutch Cup|Netherlands",
"240":"Danmarksserien|Denmark",
"242":"Ekstra Bladet Cup|Denmark",
"247":"Community Shield|England",
"250":"Formuladeildin|Faroe Islands",
"251":"Ykkonen|Finland",
"253":"Druha League|Czech Republic",
"254":"Czech Cup|Czech Republic",
"264":"Second Division|Belgium",
"268":"Serie A|Brazil",
"270":"A Grupa|Bulgaria",
"278":"Austrian Cup|Austria",
"287":"EURO Championship U-19|Europe",
"288":"EURO Championship U-21|Europe",
"289":"Africa Cup of Nations|International",
"296":"World Cup U-20|International",
"297":"CONCACAF Champions Cup|Club International",
"298":"CONCACAF Gold Cup|International",
"299":"Copa Sudamericana|Club International",
"301":"EURO Championship U-17|Europe",
"306":"World Cup U-17|International",
"329":"Gulf Cup|International",
"338":"National League|Russia",
"342":"League Cup|Finland",
"440":"Super Cup|Japan",
"441":"Premier League|Ukraine",
"461":"S. League|Singapore",
"489":"Club Friendlies|Friendlies",
//"512":"Oberliga|Germany",
"513":"Lig 2|Turkey",
"525":"AFC Champions League|Club International",
"8814":"Serie B|Brazil",
"8815":"B Ethniki|Greece",
"8965":"Primera B Nacional|Argentina",
"8968":"Segunda B|Spain",
"8970":"National|France",
"8972":"USL 1|United States",
"8973":"Division 1|Slovakia",
"8976":"Ascenso MX|Mexico",
"8978":"League Cup|Northern Ireland"
};